config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  root "homes#index"
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  resources :users, only: %i(show) do
    resources :orders, only: %i(index)
    resources :parkings, except: %i(index)
  end
  concern :paginatable do
    get "(page/:page)", action: :index, on: :collection, as: ""
  end
  resources :parkings, only: %i(index), concerns: :paginatable
  get "search(/:search)", to: "searches#index", as: :search
  resources :places
  resources :parkings do
    resources :orders, except: %i(show edit)
    resources :reviews, except: %i(index)
  end
  resources :reviews, only: %i(index)
end

app/models/parking.rb
class Parking < ApplicationRecord
  belongs_to :user
  has_many :orders, as: :orderable
  has_many :users, through: :orders
  has_many :reviews
  has_many :users, through: :reviews

  validates :name, presence: true, length: { maximum: Settings.name_max },
    uniqueness: true
  validates :total_position, presence: true, numericality: { greater_than: Settings.total_position_min}
  validates :longitude, presence: true
  validates :latitude, presence: true
  validates :address, presence: true
  validates :price, presence: true, numericality: { greater_than: Settings.price_min}
  scope :order_by_time, -> {order created_at: :desc}
  geocoded_by :address
end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController
  before_action :set_user, except: %i(index)
  before_action :set_parking, only: %i(show edit update destroy)
  before_action :authenticate_user!, except: %i(index show)
  before_action :set_current_user, only: %i(new edit)

  def index
    @parkings = Parking.all.order_by_time.page(params[:page])
  end

  def new
    @parking = @user.build_parking
  end

  def create
    @parking = @user.build_parking(parking_params)
    @parking.avail_position = params[:parking][:total_position]
    if @parking.save
      flash[:success] = t("parkings.create_park_success")
      redirect_to user_parking_path(@user, @parking)
    else
      flash[:danger] = t("parkings.create_park_fail")
      render :new
    end
  end

  def show
    if !@user.current_user?(current_user) && current_user
      @orders = current_user.orders.find_order(@parking.id, t("parkings.parking"))
    end
  end

  def edit
  end

  def update
    if @parking.update(parking_params)
      @parking.update status: params[:parking][:status]
      flash[:success] = t("parkings.update_park_success")
      redirect_to user_parking_path(@user, @parking)
    else
      flash[:danger] = t("parkings.update_park_fail")
      render :edit
    end
  end

  def destroy
    if @parking.destroy
      flash[:success] = t("parkings.del_park_success")
    else
      flash[:danger] = t("parkings.del_park_fail")
    end
    redirect_to root_url
  end

  private

  def parking_params
    params.require(:parking).permit :name, :waiting_time, :description,
      :total_position, :longitude, :latitude, :address, :time_open,
      :time_close, :price
  end

  def set_user
    @user = User.find_by(id: params[:user_id])
    return if @user
    flash[:danger] = t("users.not_find_user")
    redirect_to root_url
  end

  def set_parking
    @parking = @user.parking
    return if @parking
    flash[:danger] = t("parkings.not_find_park")
    redirect_to root_url
  end

  def set_current_user
    return if @user == current_user
    flash[:danger] = t("parkings.not_have_access_rights")
    redirect_to root_url
  end
end

app/views/parkings/_form_parking.html.erb
<div class="mainbox col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
  <div class="panel panel-success">
    <div class="panel-heading">
      <div class="panel-title"><%= title %></div>
    </div>
    <div class="panel-body">
      <%= form_for [user, parking], html: {class: "form-horizontal"} do |f| %>
        <%= f.label :name, t("parkings.name_park") %>
        <%= f.text_field :name, class: "form-control" %><br>
        <%= f.label :waiting_time, t("parkings.waiting_time") %><br>
        <%= f.select :waiting_time, [t("parkings.option1"), t("parkings.option2"),
          t("parkings.option3"), t("parkings.option4")], class: "form-control" %><br><br>
        <%= f.label :description, t("parkings.description") %>
        <%= f.text_field :description, class: "form-control" %><br>
        <%= f.label :total_position, t("parkings.total_position") %>
        <%= f.number_field :total_position, class: "form-control" %><br>
        <%= f.label :latitude, t("parkings.latitude") %>
        <%= f.text_field :latitude, class: "form-control" %><br>
        <%= f.label :longitude, t("parkings.longitude") %>
        <%= f.text_field :longitude, class: "form-control" %><br>
        <%= f.label :address, t("parkings.address") %>
        <%= f.text_field :address, class: "form-control" %><br>
        <%= f.label :time_open, t("parkings.time_open") %>
        <%= f.time_field :time_open, class: "form-control" %><br>
        <%= f.label :time_close, t("parkings.time_close") %>
        <%= f.time_field :time_close, class: "form-control" %><br>
        <% if title == t("parkings.edit_park") %>
          <%= f.label :status, t("parkings.status_park") %><br>
          <%= f.select :status, [t("parkings.open_status"),
            t("parkings.close_status")], class: "form-control" %><br><br>
        <% end %>
        <%= f.label :price, t("parkings.price") %>
        <%= f.text_field :price, class: "form-control" %><br>
        <%= f.submit t("parkings.confirm"), class: "btn btn-primary" %>
        <%= link_to t("parkings.cancel"), root_url,
          class: "btn btn-warning btn-cancel" %>
      <% end %>
    </div>
  </div>
</div>

app/views/parkings/_parking.html.erb
<p><%= parking.name %></p><br>
<p><%= parking.waiting_time %></p><br>
<p><%= parking.description %></p><br>
<p><%= parking.total_position %></p><br>
<p><%= parking.avail_position %></p><br>
<p><%= parking.longitude %></p><br>
<p><%= parking.latitude %></p><br>
<p><%= parking.address %></p><br>
<p><%= l(parking.time_open, format: :hour_minute_half_day) %></p><br>
<p><%= l(parking.time_close, format: :hour_minute_half_day) %></p><br>
<p><%= number_to_currency(parking.price) %></p><br>

app/views/parkings/edit.html.erb
<%= render "parkings/form_parking", title: t("parkings.edit_park"), user: @user,
  parking: @parking %>

app/views/parkings/index.html.erb
<%= render @parkings %>
<%= paginate @parkings, theme: "twitter-bootstrap-3" %>

app/views/parkings/new.html.erb
<%= render "parkings/form_parking", title: t("parkings.add_park"), user: @user,
  parking: @parking %>

app/views/parkings/show.html.erb
<div class="row">
  <div id="map_show" class="col-md-7 col-lg-7"></div>
  <div id="detail_park" class="col-md-5 col-lg-5">
    <h2 id="park_name"><%= @parking.name %></h2><br>
    <%= social_share_button_tag(@parking.name) %>
    <h3><%= t "parkings.address" %><%= @parking.address %></h3><br>
    <h4><%= t "parkings.waiting_time" %><%= @parking.waiting_time %></h4><br>
    <h4><%= t "parkings.description" %><%= @parking.description %></h4><br>
    <h4><%= t "parkings.total_position" %><%= @parking.total_position %></h4><br>
    <h4><%= t "parkings.avail_position" %><%= @parking.avail_position %></h4><br>
    <h4><%= t "parkings.time_operation" %><%= l(@parking.time_open, format: :hour_minute_half_day) %> - <%= l(@parking.time_close, format: :hour_minute_half_day) %></h4><br>
    <h4><%= t "parkings.price" %><%= number_to_currency(@parking.price) %></h4><br>
    <p id="latitude"><%= @parking.latitude %></p>
    <p id="longitude"><%= @parking.longitude %></p>
    <% if !@parking.user.current_user?(current_user) %>
      <% if user_signed_in? && @orders.last.present? &&
        (@orders.last.booked? || @orders.last.sending?) %>
        <h4 class="alert alert-success"><%= t "orders.status_sending" %></h4><br>
      <% elsif can? :create, Order || @orders.last.nil? ||
        @orders.last.sended? || @orders.last.canceled? %>
        <%= link_to t("orders.new_order") + " - #{@parking.avail_position}",
          new_parking_order_path(@parking), class: "btn btn-info" %><br>
      <% end %>
    <% else %>
      <%= link_to edit_user_parking_path(@user, @parking),
        class: "btn btn-primary btn-edit-park" do %>
        <span class="glyphicon glyphicon-edit"></span>
        <span><strong><%= t "parkings.update_park" %></strong></span>
      <% end %>
    <% end %>
    <% if can? :destroy, @parking %>
      <%= link_to user_parking_path(@user, @parking), method: :delete,
        data: {confirm: t("parkings.confirm_del_park")}, class: "btn btn-danger" do %>
        <span class="glyphicon glyphicon-delete"></span>
        <span><strong><%= t "parkings.del_park" %></strong></span>
      <% end %>
    <% end %>
  </div>
</div>

<%= javascript_include_tag "map_show", "data-turbolinks-track": "reload" %>