config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  root "homes#index"
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  resources :users, only: %i(show) do
    resources :orders, only: %i(index)
    resources :parkings, except: %i(index)
  end
  concern :paginatable do
    get "(page/:page)", action: :index, on: :collection, as: ""
  end
  resources :parkings, only: %i(index), concerns: :paginatable
  get "search(/:search)", to: "searches#index", as: :search
  resources :places
  resources :parkings do
    resources :orders, except: %i(show edit)
    resources :reviews, except: %i(index)
  end
  resources :reviews, only: %i(index)
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse" id="header">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to t("layouts.park_booking"), root_url, class: "navbar-brand" %>
    </div>
    <ul class="nav navbar-nav">
      <li class="active">
        <%= link_to t("layouts.home_page"), root_url %>
      </li>
      <% if current_user && current_user.parking.present? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= t "layouts.collection" %><span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to t("layouts.my_park"), user_parking_path(current_user,
              current_user.parking) %></li>
            <li><%= link_to t("layouts.customer"), parking_orders_path(current_user.parking) %></li>
          </ul>
        </li>
      <% end %>
    </ul>
    <% if user_signed_in? %>
      <ul class="nav navbar-right">
        <li class="dropdown dropdown_profile">
          <a href="#" class="dropdown-toggle text-muted" data-toggle="dropdown">
            <%= image_tag(current_user.user_img.url(:user_show), class: "user_img") %>
            <%= current_user.name %> <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <% if current_user.role_id == 2 %>
              <li><%= link_to t("layouts.admin_page"), rails_admin_path %></li>
            <% end %>
            <li><%= link_to t("layouts.profile_page"), current_user %></li>
            <li><%= link_to t("layouts.logout"), destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
      <% if current_user.parking.nil? %>
        <ul class="nav navbar-nav navbar-right add_park_btn">
          <%= link_to new_user_parking_path(current_user),
            class: "btn btn-primary" do %>
            <span class="glyphicon glyphicon-plus"></span>
            <%= t "parkings.add_park" %>
          <% end %>
        </ul>
      <% end %>
    <% else %>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to new_user_session_path do %>
            <span class="glyphicon glyphicon-log-in login_tag">
            </span><%= t "sessions.login" %>
          <% end %>
        </li>
      </ul>
    <% end %>

    <%= form_tag search_path, method: :get,
      class: "navbar-form search-form", id: "livesearch_form" do %>
      <div class="form-group dropdown">
        <%= text_field_tag :search, params[:search],
          class: "form-control dropdown-toggle", placeholder: t("layouts.search"),
          "data-toggle": "dropdown", "aria-hidden": :true,
          autocomplete: :off, required: true, id: "livesearch_input" %>
        <ul class="dropdown-menu">
          <div id="livesearch_dom"></div>
        </ul>
      </div>
      <%= button_tag type: :submit, class: "btn btn-default" do %>
        <i class="fa fa-search"></i>
      <% end %>
    <% end %>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag "application", media: "all",
  "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
<script src="//maps.google.com/maps/api/js?key=AIzaSyBFieACM1ebKhQL4Dr7ZAOTbRJaMXNUtRo"></script>
<%= javascript_include_tag "markerclusterer.min", "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "infobox_packed", "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "underscore-min", "data-turbolinks-track": "reload" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= t ".title" %></title>
    <%= render "layouts/rails_default" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= render "layouts/messages" %>
      <%= yield %>
      <%= javascript_include_tag "header", "data-turbolinks-track": "reload" %>
      <%= javascript_include_tag "searchbox", "data-turbolinks-track": "reload" %>
    </div>
  </body>
</html>